### ISSUE TITLE
这横向滚动条CSS如何改才能一直显示。现在需要拉到最底下才能看到横向滚动条

### ISSUE THREAD

**Issue by lipeiyu2106** [Shimada666/v-code-diff#41]
![image](https://user-images.githubusercontent.com/67227495/190541423-be45c6a7-fc35-47a7-9e9a-7c122292f827.png)

**Comment by Shimada666** [comment]
目前只能限制高度了 + 开启滚动了。参考覆盖以下css可以临时解决问题，但如果数据不长则样式也不好看
```scss
  .d2h-file-side-diff {
    margin-bottom: -5px;
    max-height: 500px;
    overflow: scroll;
  }
  .d2h-code-side-linenumber {
    padding: 0 0.5rem;
    position: relative;
    line-height: 20px;
    height: 20px;
  }
```

过一段时间会出新版，不依赖 diff2html 的版本，新版中会解决这个问题
